<a href="https://colab.research.google.com/github/Rishirajbal/Rishirajbal/blob/main/Neural_Networks_From_scratch_SentDex_3_and_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
inputs = [1, 2, 3, 2.5]
weights = [[0.2, 0.8, -0.5, 1.0], [0.4, 0.2, -0.2, 0.5], [0.15, 0.9, -0.4, 0.2]]
bias = [2, 1, 0.5]

In [ ]:
#single weight,single input setup
import numpy as np
inputs = [1, 2, 3, 2.5]
weights =[0.2, 0.8, -0.5, 1.0]
bias =2
output = np.dot(inputs,weights)+bias
print(output)

4.8


In [ ]:
#multi-weight,single input setup
import numpy as np
inputs = [1, 2, 3, 2.5]
weights = [[0.2, 0.8, -0.5, 1.0],
            [0.4, 0.2, -0.2, 0.5],
             [0.15, 0.9, -0.4, 0.2]]
bias = [2, 1, 0.5]
output=np.dot(weights,inputs)+bias
print(output)

[4.8  2.45 1.75]


In [ ]:
#multi-weight,multi-input setup
import numpy as np
inputs = [[1, 2, 3, 2.5],
           [2.0,5.0,-1.0,2.0],
            [-1.5,2.7,3.3,-0.8]]
weights = [[0.2, 0.8, -0.5, 1.0],
            [0.4, 0.2, -0.2, 0.5],
             [0.15, 0.9, -0.4, 0.2]]
transposed_weights = np.array(weights).T
bias = [2,3, 0.5]
output=np.dot(inputs ,transposed_weights )+bias
print(output)

[[4.8   4.45  1.75 ]
 [8.9   6.    6.1  ]
 [1.41  1.88  1.225]]


In [ ]:
#multi-weight,multi-input,multi layered setup
import numpy as np
inputs = [[1, 2, 3, 2.5],
           [2.0,5.0,-1.0,2.0],
            [-1.5,2.7,3.3,-0.8]]
weights = [[0.2, 0.8, -0.5, 1.0],
            [0.4, 0.2, -0.2, 0.5],
             [0.15, 0.9, -0.4, 0.2]]
bias = [2,3, 0.5]
weights2=[[0.1,-0.14,0.5],
          [-0.5,0.12,-0.33],
           [-0.44,0.73,-0.13]]
bias2=[-1,2,-0.5]
layer_output1=np.dot(inputs,np.array(weights).T)+bias
layer_output2=np.dot(layer_output1,np.array(weights2).T)+bias2 #input_2 = layer_output2 = np.dot(inputs,np.array(weights).T)+bias

print(layer_output2)

[[-0.268   -0.4435   0.409  ]
 [ 2.1     -3.743   -0.829  ]
 [-0.5097   1.11635  0.09275]]


In [ ]:
#multi-weight,multi-input,multi layered setup,with objects
import numpy as np
np.random.seed(0)
X =[[1, 2, 3, 2.5],
      [2.0,5.0,-1.0,2.0],
        [-1.5,2.7,3.3,-0.8]]

class layer_dense:
  def __init__(self,n_inputs,n_neurons):
    self.weights=0.10*np.random.randn(n_inputs,n_neurons) # the correct would have been 0.10*np.random.randn(n_neurons,n_inputs) but in the forward method we would have to do transpose so we did it here
    self.biases=np.zeros((1,n_neurons)) # 1 is the shape and n_neurons is number of nuerons we want
  def forward(self,inputs):
       self.output=np.dot(inputs,self.weights)+self.biases

layer1=layer_dense(4,5)
layer2=layer_dense(5,5)

layer1.forward(X)
print(layer1.output)
layer2.forward(layer1.output)
print(layer2.output)

[[ 0.10758131  1.03983522  0.24462411  0.31821498  0.18851053]
 [-0.08349796  0.70846411  0.00293357  0.44701525  0.36360538]
 [-0.50763245  0.55688422  0.07987797 -0.34889573  0.04553042]]
[[-0.18969615  0.03342147 -0.02578516  0.12739327  0.14946944]
 [-0.1128111   0.00125844 -0.0290323   0.1678249   0.05300012]
 [ 0.03961535 -0.07700061 -0.11111625  0.12960619 -0.02794614]]


In [ ]:
#let's add a activation function basically turns the linear function into a curve to be able to calculate the lowest point
# example RELU
import numpy as np
np.random.seed(0)
X =[[1, 2, 3, 2.5],
      [2.0,5.0,-1.0,2.0],
        [-1.5,2.7,3.3,-0.8]]

inputs =[0,2,-1,3.3,-2.7,1.1,2.2,-100]
output=[]
for i in inputs:
  output.append(max(0,i))
print(output)

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]


In [ ]:
from typing import KeysView
import numpy as np

np.random.seed(0)

X = [[1, 2, 3, 2.5],
     [2.0, 5.0, -1.0, 2.0],
     [-1.5, 2.7, 3.3, -0.8]]

class LayerDense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))

    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases


class relu:
  def forward(self,inputs):
    self.output=np.maximum(0,inputs)

j = int(input("what is the number of hidden layers? "))
k = int(input("what is the number of outputs? "))

layer1 = LayerDense(4, j)
layer2 = LayerDense(j, k)

layer1.forward(X)
layer2.forward(layer1.output)


what is the number of hidden layers? 3
what is the number of outputs? 2
[[0.13008869 0.02097984]
 [0.15932724 0.05289362]
 [0.         0.03183967]]


In [ ]:
!pip install nnfs

In [ ]:
from typing import KeysView
import numpy as np
import nnfs
nnfs.init()

from nnfs.datasets import spiral_data

X, y = spiral_data(100, 3)

class LayerDense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))

    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

class ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

j = int(input("Number of neurons: "))

layer1 = LayerDense(2, j)
activation1 = ReLU()

layer1.forward(X)
activation1.forward(layer1.output)

print(activation1.output)

Number of neurons: 6
[[0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 6.3385908e-04 0.0000000e+00 7.0642207e-05
  9.0164586e-04]
 [0.0000000e+00 3.9957227e-05 9.2750194e-04 0.0000000e+00 6.5028836e-04
  1.0838244e-03]
 ...
 [9.2587270e-02 0.0000000e+00 2.7677365e-02 6.0882296e-02 0.0000000e+00
  6.9344796e-02]
 [1.4715683e-01 0.0000000e+00 1.5908248e-03 6.8911701e-02 0.0000000e+00
  2.9615715e-02]
 [7.8694962e-02 0.0000000e+00 3.4270126e-02 5.8806412e-02 0.0000000e+00
  7.9367116e-02]]


Softmax activation function

In [1]:
import math
E= math.e
output=[2.44,5.22,5.8594]

exp=[]
for i in output:
  exp.append(E**i)
  print(exp)


[11.473040742794831]
[11.473040742794831, 184.93418407068333]
[11.473040742794831, 184.93418407068333, 350.5137726512231]
