<a href="https://colab.research.google.com/github/Rishirajbal/Rishirajbal/blob/main/Neural_Networks_From_scratch_SentDex_3_and_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
inputs = [1, 2, 3, 2.5]
weights = [[0.2, 0.8, -0.5, 1.0], [0.4, 0.2, -0.2, 0.5], [0.15, 0.9, -0.4, 0.2]]
bias = [2, 1, 0.5]

In [ ]:
#single weight,single input setup
import numpy as np
inputs = [1, 2, 3, 2.5]
weights =[0.2, 0.8, -0.5, 1.0]
bias =2
output = np.dot(inputs,weights)+bias
print(output)

4.8


In [ ]:
#multi-weight,single input setup
import numpy as np
inputs = [1, 2, 3, 2.5]
weights = [[0.2, 0.8, -0.5, 1.0],
            [0.4, 0.2, -0.2, 0.5],
             [0.15, 0.9, -0.4, 0.2]]
bias = [2, 1, 0.5]
output=np.dot(weights,inputs)+bias
print(output)

[4.8  2.45 1.75]


In [ ]:
#multi-weight,multi-input setup
import numpy as np
inputs = [[1, 2, 3, 2.5],
           [2.0,5.0,-1.0,2.0],
            [-1.5,2.7,3.3,-0.8]]
weights = [[0.2, 0.8, -0.5, 1.0],
            [0.4, 0.2, -0.2, 0.5],
             [0.15, 0.9, -0.4, 0.2]]
transposed_weights = np.array(weights).T
bias = [2,3, 0.5]
output=np.dot(inputs ,transposed_weights )+bias
print(output)

[[4.8   4.45  1.75 ]
 [8.9   6.    6.1  ]
 [1.41  1.88  1.225]]


In [ ]:
#multi-weight,multi-input,multi layered setup
import numpy as np
inputs = [[1, 2, 3, 2.5],
           [2.0,5.0,-1.0,2.0],
            [-1.5,2.7,3.3,-0.8]]
weights = [[0.2, 0.8, -0.5, 1.0],
            [0.4, 0.2, -0.2, 0.5],
             [0.15, 0.9, -0.4, 0.2]]
bias = [2,3, 0.5]
weights2=[[0.1,-0.14,0.5],
          [-0.5,0.12,-0.33],
           [-0.44,0.73,-0.13]]
bias2=[-1,2,-0.5]
layer_output1=np.dot(inputs,np.array(weights).T)+bias
layer_output2=np.dot(layer_output1,np.array(weights2).T)+bias2 #input_2 = layer_output2 = np.dot(inputs,np.array(weights).T)+bias

print(layer_output2)

[[-0.268   -0.4435   0.409  ]
 [ 2.1     -3.743   -0.829  ]
 [-0.5097   1.11635  0.09275]]


In [ ]:
#multi-weight,multi-input,multi layered setup,with objects
import numpy as np
np.random.seed(0)
X =[[1, 2, 3, 2.5],
      [2.0,5.0,-1.0,2.0],
        [-1.5,2.7,3.3,-0.8]]

class layer_dense:
  def __init__(self,n_inputs,n_neurons):
    self.weights=0.10*np.random.randn(n_inputs,n_neurons) # the correct would have been 0.10*np.random.randn(n_neurons,n_inputs) but in the forward method we would have to do transpose so we did it here
    self.biases=np.zeros((1,n_neurons)) # 1 is the shape and n_neurons is number of nuerons we want
  def forward(self,inputs):
       self.output=np.dot(inputs,self.weights)+self.biases

layer1=layer_dense(4,5)
layer2=layer_dense(5,5)

layer1.forward(X)
print(layer1.output)
layer2.forward(layer1.output)
print(layer2.output)

[[ 0.10758131  1.03983522  0.24462411  0.31821498  0.18851053]
 [-0.08349796  0.70846411  0.00293357  0.44701525  0.36360538]
 [-0.50763245  0.55688422  0.07987797 -0.34889573  0.04553042]]
[[-0.18969615  0.03342147 -0.02578516  0.12739327  0.14946944]
 [-0.1128111   0.00125844 -0.0290323   0.1678249   0.05300012]
 [ 0.03961535 -0.07700061 -0.11111625  0.12960619 -0.02794614]]


In [ ]:
#let's add a activation function basically turns the linear function into a curve to be able to calculate the lowest point
# example RELU
import numpy as np
np.random.seed(0)
X =[[1, 2, 3, 2.5],
      [2.0,5.0,-1.0,2.0],
        [-1.5,2.7,3.3,-0.8]]

inputs =[0,2,-1,3.3,-2.7,1.1,2.2,-100]
output=[]
for i in inputs:
  output.append(max(0,i))
print(output)

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]


In [ ]:
from typing import KeysView
import numpy as np

np.random.seed(0)

X = [[1, 2, 3, 2.5],
     [2.0, 5.0, -1.0, 2.0],
     [-1.5, 2.7, 3.3, -0.8]]

class LayerDense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))

    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases


class relu:
  def forward(self,inputs):
    self.output=np.maximum(0,inputs)

j = int(input("what is the number of hidden layers? "))
k = int(input("what is the number of outputs? "))

layer1 = LayerDense(4, j)
layer2 = LayerDense(j, k)

layer1.forward(X)
layer2.forward(layer1.output)


what is the number of hidden layers? 3
what is the number of outputs? 2
[[0.13008869 0.02097984]
 [0.15932724 0.05289362]
 [0.         0.03183967]]


In [12]:
!pip install nnfs

In [7]:
from typing import KeysView
import numpy as np
import nnfs
nnfs.init()
from nnfs.datasets import spiral_data
np.random.seed(0)


X, y = spiral_data(100, 3)
class layer_output:
  def __init__(self,n_inputs,n_neurona):
    self.weights=0.10*np.random.randn(n_inputs,n_neurona)
    self.biases=np.zeros((1,n_neurona))
  def forward(self,inputs):
    self.ouputs=np.dot(inputs,self.weights)+self.biases

class RELU:
  def forward(self,inputs):
    self.outputs=np.maximum(0,inputs)

k= int(input("enter the number of neurons"))
layer1=layer_output(2,k)
activation1=RELU()
layer1.forward(X)
activation1.forward(layer1.ouputs)
print(activation1.outputs)


enter the number of neurons7
[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.00116596 0.         ... 0.00123928 0.         0.        ]
 [0.         0.00321554 0.         ... 0.00253564 0.         0.        ]
 ...
 [0.09229197 0.         0.00745169 ... 0.         0.017093   0.10952952]
 [0.1473361  0.         0.01386877 ... 0.         0.06133506 0.1411885 ]
 [0.07827959 0.         0.00582034 ... 0.         0.00586882 0.10143228]]


Softmax activation function

In [ ]:
#softmax activation function hardcode
import math
E= math.e
output=[2.44,5.22,5.8594]

exp=[]
for i in output:
  exp.append(E**i)
print(exp)#exponantiation


norm_base=sum(exp)
norm=[]
for i in exp:
  norm.append(i/norm_base)
print(norm)#normalisation

print(sum(norm))

[11.473040742794831, 184.93418407068333, 350.5137726512231]
[0.020977510090084465, 0.3381369245795306, 0.640885565330385]
1.0


In [8]:
import numpy as np
import nnfs

layer_outputs= [[4.8,1.21,2.385],
                [8.9,-1.81,0.2],
                [1.41,1.051,0.026]]
exp_values = np.exp(layer_outputs)
normal_val= exp_values/np.sum(exp_values,axis=1,keepdims=True)
print(normal_val)
'''exp_values = np.exp(layer_outputs)
print(exp_values)

normal_val= exp_values/np.sum(exp_values)
print(normal_val)'''

[[8.95282664e-01 2.47083068e-02 8.00090293e-02]
 [9.99811129e-01 2.23163963e-05 1.66554348e-04]
 [5.13097164e-01 3.58333899e-01 1.28568936e-01]]


'exp_values = np.exp(layer_outputs)\nprint(exp_values)\n\nnormal_val= exp_values/np.sum(exp_values)\nprint(normal_val)'

In [16]:
from typing import KeysView
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()
np.random.seed(0)

class LayerDense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))

    def forward(self, inputs):
        self.outputs = np.dot(inputs, self.weights) + self.biases


class RELU:
    def forward(self, inputs):
        self.outputs = np.maximum(0, inputs)


class Softmax:
    def forward(self, inputs):
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))  # Subtract max for numerical stability
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.outputs = probabilities


# User input for neurons in the layers
k = int(input("Enter the number of neurons in the first layer: "))
p = int(input("Enter the number of neurons in the output layer: "))

# Generate dataset
X, y = spiral_data(samples=100, classes=3)

# Forward pass through the first layer
layer1 = LayerDense(2, k)
activation1 = RELU()
layer1.forward(X)
activation1.forward(layer1.outputs)

# Forward pass through the second layer
layer2 = LayerDense(k, p)
layer2.forward(activation1.outputs)

# Forward pass through softmax activation
activation2 = Softmax()
activation2.forward(layer2.outputs)

# Print the softmax output
print("Softmax output:")
print(activation2.outputs)


Enter the number of neurons in the first layer: 9
Enter the number of neurons in the output layer: 7
Softmax output:
[[0.14285715 0.14285715 0.14285715 ... 0.14285715 0.14285715 0.14285715]
 [0.14287454 0.14284727 0.14283878 ... 0.14284484 0.14287548 0.14284901]
 [0.14287461 0.14283906 0.14287437 ... 0.14285246 0.14290208 0.14280756]
 ...
 [0.1457957  0.14330728 0.14088179 ... 0.14116937 0.14439568 0.14134444]
 [0.14618595 0.14435534 0.141594   ... 0.14108536 0.14362057 0.14140147]
 [0.14571458 0.14303394 0.14067398 ... 0.1411752  0.14460658 0.14132953]]
